export const RESPONSE_CODES = {
    RESOURCE_CREATED: "RESOURCE_CREATED",
    RESOURCE_UPDATED: "RESOURCE_UPDATED",
    RESOURCE_DELETED: "RESOURCE_DELETED",
    RESOURCE_FOUND: "RESOURCE_FOUND",
    RESOURCE_LISTED: "RESOURCE_LISTED",

    BAD_REQUEST: "BAD_REQUEST",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT",
    INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;
export type ResponseCodes = (typeof RESPONSE_CODES)[keyof typeof RESPONSE_CODES];
